<#import "./module/class.ftl" as clazz>
<#if packageName??>
package ${packageName};

</#if>
<#if deprecated>
@java.lang.Deprecated
</#if>
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Craft IDL Compiler (${version})", date = "${date?datetime}")
<@clazz.class className=className fields=fields static=false />