package ${packageName};

/**
* Autogenerated by Craft Compiler (${version})
* Compile date ${date?datetime}
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*  @generated
*/
<#if deprecated>
@java.lang.Deprecated
</#if>
public enum ${className} implements org.apache.thrift.TEnum {

    <#list fields as field>
    <#if field.deprecated>
    @java.lang.Deprecated
    </#if>
    ${field.name}(${field.sequence}),

    </#list>
    ;

    private final int value;

    ${className}(int value) {
        this.value = value;
    }

    /**
    * Get the integer value of this enum value, as defined in the Thrift IDL.
    */
    @Override
    public int getValue() {
        return value;
    }

    /**
    * Find a the enum type by its integer value, as defined in the Thrift IDL.
    * @return null if the value is not found.
    */
    public static ${className} findByValue(int value) {
        switch (value) {
            <#list fields as field>
            case ${field.sequence}:
                return ${field.name};
            </#list>
            default:
                return null;
        }
    }
}